import { SearchRecipe } from "@/types";

const wordsToPromote = [
  "split",
  "array",
  "variable",
  "hoist",
  "closure",
  "callback",
  "promise",
  "async",
  "await",
  "loop",
  "condition",
  "scope",
  "prototype",
  "object",
  "function",
  "event",
  "debugger",
  "console",
  "stack",
  "trace",
  "try",
  "catch",
  "throw",
  "finally",
  "regex",
  "token",
  "parser",
  "let",
  "const",
  "var",
  "arrowfunction",
  "this",
  "class",
  "constructor",
  "super",
  "module",
  "import",
  "export",
  "require",
  "listener",
  "fetch",
  "json",
  "dom",
  "window",
  "document",
  "localstorage",
  "sessionstorage",
  "queryselector",
  "addeventlistener",
  "settimeout",
  "setinterval",
  "cleartimeout",
  "clearinterval",
  "map",
  "filter",
  "reduce",
  "foreach",
  "hoisting",
  "iife",
  "templateliteral",
  "spread",
  "rest",
  "destructure",
  "nan",
  "undefined",
  "null",
  "typeof",
  "instanceof",
  "symbol",
  "iterator",
  "generator",
  "strictmode",
  "eval",
  "type",
  "interface",
  "enum",
  "namespace",
  "declare",
  "implements",
  "extends",
  "readonly",
  "private",
  "protected",
  "public",
  "abstract",
  "generic",
  "typealias",
  "uniontype",
  "intersectiontype",
  "literaltype",
  "tuple",
  "mappedtype",
  "typeinference",
  "typeassertion",
  "as",
  "unknown",
  "any",
  "never",
  "void",
  "strict",
  "noimplicitany",
  "compiler",
  "transpile",
  "decorator",
  "emit",
  "typeguard",
  "optionalchaining",
  "nullishcoalescing",
  "nonnullable",
  "controlflowanalysis",
  "moduleresolution",
  "ambientdeclaration",
  "pathalias",
  "strictnullchecks",
  "tsconfig",
  "target",
  "lib",
  "esnext",
  "jsx",
  "compiletime",
  "moduleaugmentation",
  "keyof",
  "in",
  "partial",
  "required",
  "pick",
  "omit",
  "record",
  "returntype",
  "parameters",
  "constructorparameters",
];

export const recipe: SearchRecipe = {
  name: "Programming",
  description: "Debuging.",
  svgIcon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path fill="currentColor" d="M20 4H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h16c1.1 0 2-.9 2-2V6a2 2 0 0 0-2-2m0 14H4V8h16zm-8-2c0-.55.45-1 1-1h4c.55 0 1 .45 1 1s-.45 1-1 1h-4c-.55 0-1-.45-1-1M6.79 9.71a.996.996 0 0 1 1.41 0l2.59 2.59c.39.39.39 1.02 0 1.41L8.2 16.3a.996.996 0 1 1-1.41-1.41L8.67 13l-1.88-1.88a.996.996 0 0 1 0-1.41"/></svg>`,
  byLang: {
    pl: {
      name: "Programowanie",
      description: "Debugowanie.",
    },
  },
  wordsToPromote: wordsToPromote,
  wordsToIgnore: [],
  options: [
    {
      domain: "https://www.duckduckgo.com/",
      getSearchUrl: (phrase, key) =>
        `https://duckduckgo.com/?q=${encodeURI(
          `${phrase} site:stackoverflow.com`
        )}&shoukaiKey=${key}`,
    },
    {
      domain: "https://www.google.com/",
      getSearchUrl: (phrase, key) =>
        `https://www.google.com/search?q=${encodeURI(
          `${phrase} site:stackoverflow.com`
        )}&shoukaiKey=${key}`,
    },
  ],
  minimumScore: 0,
};
